all:
  children:
    pb_home:
      hosts:
        host74.nird.club:
          ansible_user: ansible
          ansible_ssh_private_key_file: ~/.ssh/keys/nirdclub__id_ed25519
        host78.nird.club:
          ansible_user: ansible
          ansible_ssh_private_key_file: ~/.ssh/keys/nirdclub__id_ed25519
        host79.nird.club:
          ansible_user: ansible
          ansible_ssh_private_key_file: ~/.ssh/keys/nirdclub__id_ed25519
      vars:
        ansible_python_interpreter: /usr/bin/python3
        app_name: rantoo
        app_user: rantoo
        app_group: rantoo
        app_directory: /opt/rantoo
        app_port: 33080
